# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e1658572c33ac5e90d0ed44d206b20188e026b1e121e6d05f7f9606418c3ca79d012b27d5829d65a49ccabc4188a61256504bcb6ea70ada27771ed9a56580b53

test:
  secret_key_base: 8f8f8c953dd7d45b016cbfe4a17de034c738a95269762df6e29d3eec6941a550330cdcc62796bfc6cde1fdc349f01d2e797844342641c6d8270bb60698366843

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
